# Streamlit
# https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[theme]
layout="wide"

#font = "cool-font, fallback-cool-font, sans-serif"
font = "theme/Roboto/Roboto-Black.ttf"

#headingFont = [
#    "2.75rem", # h1 (1.5rem for sidebar)
#    "2.25rem", # h2 (1.25rem for sidebar)
#    "1.75rem", # h3 (1.125rem for sidebar)
#    "1.5rem", # h4 (1rem for sidebar)
#    "1.25rem", # h5 (0.875rem for sidebar)
#    "1rem", # h6 (0.75rem for sidebar)
#]

[client]
toolbarMode = "viewer"

[ui]
hideTopBar = true
hideSidebarHeader = true
hideFooter = true