models:
  - name: "Gemini 2.0"
    model_name: "Gemini 2.0 Flash Live Image Preview"
    api_name: "gemini-2.0-flash-live"
    model_availability_start_date: "April 9, 2025"
    model_availability_end_date: "April 9, 2026"
    knowledge_cutoff: "June 2024"
    context:
      input_modalities:
        - "Audio"
        - "Video"
      output_modalities:
        - "Audio"
      input_max_tokens: 32768
      output_max_tokens: 8192
    location:
      - "Global"
      - "US-Region"
      - "Europe"
    model_features:
      - "Live API"
      - "Code execution"
      - "System instructions"
      - "Function calling"
      - "Grounding with Google Search"
    pricing:
      input:
        text: "$ 1.0 / 1 M Tokens"
        audio: "$ 4.0 / 1 M Tokens"
        video: "$ 4.0 / 1 M Tokens"
        image: "$ 2.0 / 1 M Tokens"
      output:
        text: "$ 3.0 / 1 M Tokens"
        audio: "$ 16.0 / 1 M Tokens"
        video: "$ 16.0 / 1 M Tokens"
        image: "$ 8.0 / 1 M Tokens"
    sdks:
      - lang: Python
        url: "https://github.com/googleapis/python-genai/"
        version: "google-genai v1.39.1"
      - lang: Go
        url: "https://github.com/googleapis/go-genai"
        version: "go-genai v1.26.0"
      - lang: NodeJS
        url: "https://github.com/googleapis/js-genai"
        version: "@google-genai v1.22.0"
      - lang: Java
        url: "https://github.com/googleapis/java-genai"
        version: "google-genai v1.18.0"
    adk:
      - lang: Python
        url: "https://github.com/google/adk-python"
        version: "google-adk v1.15.1"
      - lang: Java
        url: "https://github.com/google/adk-java"
        version: "google-adk v0.3.0"

  - name: "Gemini 2.5"
    model_name: "Gemini 2.5 Pro"
    api_name: "gemini-2.5-pro"
    model_availability_start_date: "May 15, 2025"
    model_availability_end_date: "September 12, 2025"
    knowledge_cutoff: "September, 2024"
    context:
      input_modalities:
        - "Text"
        - "Audio"
        - "Video"
        - "Image"
      output_modalities:
        - "Text"
        - "Audio"
        - "Video"
        - "Image"
      input_max_tokens: 1048576
      output_max_tokens: 16384
    location:
      - "Global"
      - "United States"
      - "Europe"
    model_features:
      - "Live API"
      - "Code execution"
      - "System instructions"
      - "Function calling"
      - "Grounding with Google Search"
    pricing:
      input:
        text: "$ 1.0 / 1 M Tokens"
        audio: "$ 4.0 / 1 M Tokens"
        video: "$ 4.0 / 1 M Tokens"
        image: "$ 2.0 / 1 M Tokens"
      output:
        text: "$ 3.0 / 1 M Tokens"
        audio: "$ 16.0 / 1 M Tokens"
        video: "$ 16.0 / 1 M Tokens"
        image: "$ 8.0 / 1 M Tokens"
    sdks:
      - lang: Python
        url: "https://github.com/googleapis/python-genai/"
        version: "google-genai v1.39.1"
      - lang: Go
        url: "https://github.com/googleapis/go-genai"
        version: "go-genai v1.26.0"
      - lang: NodeJS
        url: "https://github.com/googleapis/js-genai"
        version: "@google-genai v1.22.0"
      - lang: Java
        url: "https://github.com/googleapis/java-genai"
        version: "google-genai v1.18.0"
    adk:
      - lang: Python
        url: "https://github.com/google/adk-python"
        version: "google-adk v1.15.1"
      - lang: Java
        url: "https://github.com/google/adk-java"
        version: "google-adk v0.3.0"