
models:
  - name: "Gemini 2.0"
    model_name: "Gemini 2.0 Flash Live"
    api_name: "gemini-2.0-flash-live"
    model_availability: "April 9, 2025 - NA"
    knowledge_cutoff: "June 2024"
    context:
      input_modalities:
        - "Audio"
        - "Video"
      output_modalities:
        - "Audio"
      input_max_tokens: 32768
      output_max_tokens: 8192
    location:
      - "Global"
      - "US-Region"
      - "Europe"
    model_features:
      - "Live API"
      - "Code execution"
      - "System instructions"
      - "Function calling"
      - "Grounding with Google Search"
    pricing:
      input:
        text: 0.5
        audio: 3.0
        video: 3.0
      output:
        text: 2.0
        audio: 12.0
    sdks:
      Python: "<a href='https://github.com/googleapis/python-genai/'>google-genai v1.39.1</a>"
      Go: "<a href='https://github.com/googleapis/go-genai'>go-genai v1.26.0</a>"
      NodeJS: "<a href='https://github.com/googleapis/js-genai'>@google-genai v1.22.0</a>"
      Java: "<a href='https://github.com/googleapis/java-genai'>google-genai v1.18.0</a>"
    adk:
      Python: "<a href='https://github.com/google/adk-python'>google-adk v1.15.1</a>"
      Java: "<a href='https://github.com/google/adk-java'>google-adk v0.3.0</a>"

  - name: "Gemini 2.5"
    model_name: "Gemini 2.5 Pro"
    api_name: "gemini-2.5-pro"
    model_availability: "May 15, 2025"
    knowledge_cutoff: "September 2024"
    context:
      input_modalities:
        - "Text"
        - "Audio"
        - "Video"
        - "Image"
      output_modalities:
        - "Text"
        - "Audio"
        - "Video"
        - "Image"
      input_max_tokens: 1048576
      output_max_tokens: 16384
    location:
      - "Global"
      - "United States"
      - "Europe"
    model_features:
      - "Live API"
      - "Code execution"
      - "System instructions"
      - "Function calling"
      - "Grounding with Google Search"
    pricing:
      input:
        text: 1.0
        audio: 4.0
        video: 4.0
        image: 2.0
      output:
        text: 3.0
        audio: 16.0
        video: 16.0
        image: 8.0
    sdks:
      Python: "<a href='https://github.com/googleapis/python-genai/'>google-genai v1.39.1</a>"
      Go: "<a href='https://github.com/googleapis/go-genai'>go-genai v1.26.0</a>"
      NodeJS: "<a href='https://github.com/googleapis/js-genai'>@google-genai v1.22.0</a>"
      Java: "<a href='https://github.com/googleapis/java-genai'>google-genai v1.18.0</a>"
    adk:
      Python: "<a href='https://github.com/google/adk-python'>google-adk v1.15.1</a>"
      Java: "<a href='https://github.com/google/adk-java'>google-adk v0.3.0</a>"
