#!/usr/bin/env python3
"""Generate ``docs/llms-full.txt`` from ``docs/llms.txt``.

``llms.txt`` is the hand-curated, link-first index of the site. This script
mirrors that exact ordering into ``llms-full.txt`` but inlines the *full*
Markdown content of every linked page, so an agent can ingest the whole site in
one fetch. Run it whenever content changes:

    python scripts/gen_llms_full.py   # or: make llms

It keeps the two files in parity: what a human sees in the nav == what an agent
gets, in the same order.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
SITE_URL = "https://msampathkumar.github.io/"

LINK_RE = re.compile(
    r"^- \[(?P<title>[^\]]+)\]\((?P<url>[^)]+)\)(?::\s*(?P<desc>.*))?$"
)
FRONT_MATTER_RE = re.compile(r"^---\s*\n.*?\n---\s*\n", re.DOTALL)


def url_to_docfile(url: str) -> Path | None:
    """Map a public URL back to its source Markdown file under docs/."""
    if not url.startswith(SITE_URL):
        return None
    path = url[len(SITE_URL) :].strip("/")
    if not path:
        return DOCS / "index.md"
    for candidate in (
        DOCS / f"{path}.md",
        DOCS / path / "index.md",
        DOCS / path / "README.md",
    ):
        if candidate.exists():
            return candidate
    return None


def strip_front_matter(text: str) -> str:
    return FRONT_MATTER_RE.sub("", text, count=1).strip()


def main() -> int:
    index = DOCS / "llms.txt"
    out = DOCS / "llms-full.txt"
    lines = index.read_text(encoding="utf-8").splitlines()

    parts: list[str] = [
        "# Sampath Kumar | AI & Cloud Blog — full content for LLMs",
        "",
        "> Full inlined Markdown of every page listed in /llms.txt, in the same",
        "> order. Generated by scripts/gen_llms_full.py — do not edit by hand.",
        "",
    ]
    missing: list[str] = []

    for line in lines:
        match = LINK_RE.match(line.strip())
        if not match:
            # Pass through section headers (##) for structure.
            if line.startswith("#"):
                parts.append(line)
            continue
        title, url = match["title"], match["url"]
        doc = url_to_docfile(url)
        if doc is None:
            missing.append(url)
            continue
        content = strip_front_matter(doc.read_text(encoding="utf-8"))
        parts.extend(["", f"## {title}", f"Source: {url}", "", content, "", "---"])

    out.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)} ({out.stat().st_size:,} bytes)")
    if missing:
        print("WARNING: could not resolve these URLs to docs files:", file=sys.stderr)
        for url in missing:
            print(f"  - {url}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
